/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-variant': '#d6e4f3',
        'surface-bright': '#f6f9ff',
        'inverse-primary': '#a7c9f4',
        'on-secondary-fixed': '#001c3b',
        'tertiary-fixed-dim': '#a5c8ff',
        'tertiary': '#001e3e',
        'on-tertiary-fixed-variant': '#004786',
        'secondary-fixed': '#d5e3ff',
        'on-surface': '#0f1d28',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#42474e',
        'outline-variant': '#c3c7cf',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#ecf4ff',
        'on-secondary-container': '#00376c',
        'outline': '#73777f',
        'surface-container-high': '#dbeaf9',
        'on-secondary-fixed-variant': '#004787',
        'inverse-surface': '#24323d',
        'on-primary': '#ffffff',
        'secondary-container': '#5ea2fe',
        'primary-fixed-dim': '#a7c9f4',
        'inverse-on-surface': '#e6f2ff',
        'primary-fixed': '#d1e4ff',
        'tertiary-fixed': '#d4e3ff',
        'surface-container': '#e1f0ff',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#003363',
        'secondary-fixed-dim': '#a6c8ff',
        'secondary': '#005eb1',
        'primary-container': '#0b3558',
        'on-primary-container': '#7c9ec7',
        'surface-container-highest': '#d6e4f3',
        'background': '#f6f9ff',
        'on-tertiary-fixed': '#001c3a',
        'on-tertiary-container': '#519dfb',
        'on-error': '#ffffff',
        'surface-tint': '#3e6186',
        'on-background': '#0f1d28',
        'error-container': '#ffdad6',
        'primary': '#001f3a',
        'surface': '#f6f9ff',
        'on-primary-fixed': '#001d35',
        'error': '#ba1a1a',
        'on-error-container': '#93000a',
        'surface-dim': '#cddceb',
        'on-primary-fixed-variant': '#25496d',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        'chat-max-width': '800px',
        unit: '8px',
        'container-padding': '24px',
        md: '16px',
        'sidebar-width': '280px',
        lg: '24px',
        xl: '32px',
      },
      fontFamily: {
        sans: ['Be Vietnam Pro', 'system-ui', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        'be-vietnam': ['Be Vietnam Pro', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-xl': ['40px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
      },
      maxWidth: {
        'chat': '800px',
      },
      boxShadow: {
        'card': '0 4px 12px rgba(11, 53, 88, 0.06)',
        'card-sm': '0 4px 12px rgba(11, 53, 88, 0.04)',
        'panel': '0 -4px 12px rgba(0, 0, 0, 0.05)',
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.35s ease-out',
        'fade-in': 'fadeIn 0.2s ease-out',
      },
    },
  },
  plugins: [],
};
