"""Closed public values used by the Week 8 calculator contracts."""

from enum import StrEnum


class ContractType(StrEnum):
    INDEFINITE = "INDEFINITE"
    FIXED_TERM_12_TO_36_MONTHS = "FIXED_TERM_12_TO_36_MONTHS"
    FIXED_TERM_UNDER_12_MONTHS = "FIXED_TERM_UNDER_12_MONTHS"


class ContractDurationType(StrEnum):
    INDEFINITE = "INDEFINITE"
    FIXED_TERM = "FIXED_TERM"


class EmployeeRole(StrEnum):
    STANDARD = "STANDARD"
    SPECIAL_OCCUPATION = "SPECIAL_OCCUPATION"


class NoticeSpecialCase(StrEnum):
    NONE = "NONE"
    WORK_OR_LOCATION_NOT_AS_AGREED = "WORK_OR_LOCATION_NOT_AS_AGREED"
    UNPAID_OR_LATE_WAGES = "UNPAID_OR_LATE_WAGES"
    MISTREATMENT_OR_FORCED_LABOR = "MISTREATMENT_OR_FORCED_LABOR"
    WORKPLACE_SEXUAL_HARASSMENT = "WORKPLACE_SEXUAL_HARASSMENT"
    PREGNANT_WORKER_MEDICAL_CERTIFICATION = "PREGNANT_WORKER_MEDICAL_CERTIFICATION"
    RETIREMENT_AGE_MET = "RETIREMENT_AGE_MET"
    EMPLOYER_DISHONEST_INFORMATION = "EMPLOYER_DISHONEST_INFORMATION"
    SPECIAL_OCCUPATION_EXTERNAL_REGULATION = "SPECIAL_OCCUPATION_EXTERNAL_REGULATION"


class DurationUnit(StrEnum):
    CALENDAR_DAYS = "calendar_days"
    WORKING_DAYS = "working_days"
    NO_NOTICE = "no_notice"


class RuleSupportStatus(StrEnum):
    SUPPORTED = "SUPPORTED"
    EXTERNAL_REGULATION_REQUIRED = "EXTERNAL_REGULATION_REQUIRED"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"


class ContractLimitStatus(StrEnum):
    WITHIN_LIMIT = "WITHIN_LIMIT"
    AT_LIMIT = "AT_LIMIT"
    EXCEEDS_LIMIT = "EXCEEDS_LIMIT"
    NOT_APPLICABLE = "NOT_APPLICABLE"
