"""Closed contracts for citation verification."""

from enum import StrEnum


class VerificationStatus(StrEnum):
    SUPPORTED = "SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    UNSUPPORTED = "UNSUPPORTED"
    INSUFFICIENT_CONTEXT = "INSUFFICIENT_CONTEXT"


class ReasonCode(StrEnum):
    MISSING_CITATION = "MISSING_CITATION"
    CITATION_NOT_FOUND = "CITATION_NOT_FOUND"
    CITATION_NOT_IN_RETRIEVED_CONTEXT = "CITATION_NOT_IN_RETRIEVED_CONTEXT"
    MALFORMED_CITATION = "MALFORMED_CITATION"
    LEGAL_REFERENCE_MISMATCH = "LEGAL_REFERENCE_MISMATCH"
    NUMERIC_CONTRADICTION = "NUMERIC_CONTRADICTION"
    PARTIAL_EVIDENCE = "PARTIAL_EVIDENCE"
    LOW_SEMANTIC_SUPPORT = "LOW_SEMANTIC_SUPPORT"
    JUDGE_UNAVAILABLE = "JUDGE_UNAVAILABLE"
    JUDGE_INVALID_OUTPUT = "JUDGE_INVALID_OUTPUT"
    OUT_OF_SCOPE_REFUSAL = "OUT_OF_SCOPE_REFUSAL"
